config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'hotsprings/top' => 'hotsprings#top'
  get 'hotsprings/:hotspring_id/likes' => 'likes#create'
  get 'hotsprings/:hotspring_id/likes/:id' => 'likes#destroy'
  resources :hotsprings
  resources :hotsprings do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  root 'hotsprings#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :hotspring
end

app/models/hotspring.rb
class Hotspring < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    has_one_attached :image_top
    has_many_attached :images
    

    # Active Storageのバリデーション
    validates :image_top, :images, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                                    size: { less_than: 5.megabytes,    
                                            message: "should be less than 5MB" }

                                            
    # image_top のリサイズ済み画像を返す
    def resize_image_top
        image_top.variant(resize_to_limit: [500, 200])
    end
end 

app/models/hotspring_tag_relation.rb
class HotspringTagRelation < ApplicationRecord
  belongs_to :hotspring
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :hotspring
  belongs_to :user
  validates_uniqueness_of :hotspring_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :hotspring_tag_relations, dependent: :destroy
    has_many :hotsprings, through: :hotspring_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hotsprings, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_hotsprings, through: :likes, source: :hotspring
  has_many :comments, dependent: :destroy
  def already_liked?(hotspring)
    self.likes.exists?(hotspring_id: hotspring.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    hotspring = Hotspring.find(params[:hotspring_id])
    comment = hotspring.comments.build(comment_params) 
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) 
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) 
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/hotsprings_controller.rb
class HotspringsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def top
    end
    def index
      if params[:search] != nil && params[:search] != ''
        search = params[:search]
        @hotsprings = Hotspring.joins(:user).where("email LIKE ? OR name LIKE ? OR point LIKE ? OR spot LIKE ? OR fee LIKE ? OR service LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      else
        @hotsprings = Hotspring.all
      end
    end

    def new
      @hotspring = Hotspring.new
    end
    
      def create
        hotspring = Hotspring.new(hotspring_params)
        hotspring.user_id = current_user.id
        if hotspring.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def show
        @hotspring = Hotspring.find(params[:id])
        @comments = @hotspring.comments
        @comment = Comment.new
      end

      def edit
        @hotspring = Hotspring.find(params[:id])
      end
      def update
        hotspring = Hotspring.find(params[:id])
        if hotspring.update(hotspring_params)
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def destroy
        hotspring = Hotspring.find(params[:id])
        hotspring.destroy
        redirect_to action: :index
      end

      private
      def hotspring_params
        params.require(:hotspring).permit(:name, :fee, :point, :spot, :service, :image_top , :images, tag_ids: [])
      end
    end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(hotspring_id: params[:hotspring_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(hotspring_id: params[:hotspring_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hotsprings_helper.rb
module HotspringsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/hotsprings/edit.html.erb
<h1>温泉日記</h1>
<%= form_for @hotspring do |f| %>
    <%= f.label :温泉名 %>
    <%= f.text_field :name, :size => 50 %><br>
    <%= f.label :料金 %>
    <%= f.text_field :fee, :size => 50 %><br>
    <%= f.label :おすすめポイント %>
    <%= f.text_field :point, :size => 50 %><br>
    <%= f.label :場所 %>
    <%= f.text_field :spot, :size => 50 %><br>
    <%= f.label :施設 %>
    <%= f.text_field :service, :size => 50 %><br>
    <%= f.submit "編集する" %>
  <% end %>

app/views/hotsprings/index.html.erb
<div id="index">
  <div class="search">
    <div class="i-text">投稿を検索</div>
    <%= form_tag({controller:"hotsprings",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索する'  %>
    <% end %>
  </div>
  
  <a href="http://localhost:3000/hotsprings/new" class="button">新規投稿ページ</a>

  <div class="hotsprings-container">
    <div class="i-text">温泉一覧</div>
    <% @hotsprings.each do |t| %>
      <div class="hotspring">
        <%= image_tag t.resize_image_top if t.image_top.attached? %>
        <div class="onsen">
          ユーザーアドレス:
          <%= t.user.email %> 
        </div>
        <div class="onsen">
          温泉名:
          <%= t.name %>
        </div>
        <div class="onsen">
          特徴:
          <%= t.point %>
        </div>
        <div class="onsen">
          住所:
          <%= t.spot %>
        </div>


        <div class="onsen">
          料金:
          <%= t.fee %>円（大人）
        </div>
        <div class="onsen">
          サービス:
          <%= t.service %>
        </div>
        <div class="onsen">
          投稿時間:
          <%= t.created_at.strftime('%Y年%m月%d日 %H時%M分')%>
        </div>

        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to hotspring_like_path(id: t.id, hotspring_id: t.id), method: :delete do %>
                <div class="font">
                  いいねを取り消す<%= t.likes.count %>
                </div>
              <% end %>
          <% else %>
            <%= link_to hotspring_likes_path(id: t.id, hotspring_id: t.id), method: :post do %>
              <div class="font">
                いいね<%= t.likes.count %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>
        <div class="i-onsen">
          <%= link_to "詳細", hotspring_path(t.id), class:"button" %>  
          <%= link_to "編集", edit_hotspring_path(t.id), class:"button" %>  
          <%= link_to "削除", hotspring_path(t.id), method: :delete, class:"button2" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/hotsprings/new.html.erb
<div id="new">
  <h3>新規投稿ページ</h3>
  <div class="post-container">
      <p class="title">投稿フォーム</p>
      <%= form_with model: @hotspring, local: true do |f| %>
        <br>
          <%= f.label :温泉名 %>
          <%= f.text_field :name, size: 140 %>
          <br>
          <br>
          <%= f.label :場所 %>
          <%= f.text_field :spot, size: 140 %>
          <br>
          <br>
          <%= f.label :料金 %>
          <%= f.text_field :fee, size: 140 %>
          <br>
          <br>
          <%= f.label :特徴 %>
          <%= f.text_field :point, size: 140 %>
          <br>
          <br>
          <%= f.label :サービス %>
          <%= f.text_field :service, size: 140 %>
          <br>
          <span class="image-top">
              <%= f.label :image_top, '画像' %>
              <%= f.file_field :image_top, accept: "image/jpeg,image/gif,image/png" %>
          </span>
          <br>
          <%= f.submit "送信" %>
      <% end %>
      <br>
      <a href="http://localhost:3000/hotsprings" class="button">温泉一覧</a>
  </div>
  <script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
      document.querySelector("#hotspring_image_top").addEventListener("change", function() {
        var size_in_megabytes = this.files[0].size / 1024 / 1024;
        if (size_in_megabytes > 5) {
          alert("Maximum file size is 5MB. Please choose a smaller file.");
          this.value = "";
        }
      });
    });
  </script>
</div>















  
  

app/views/hotsprings/show.html.erb
<h1>温泉日記</h1>
<h3>温泉の詳細</h3>
<div class="hotspring">
  <p><%= @hotspring.created_at %></p>
  <% if user_signed_in? %>
    <% if current_user.already_liked?(@hotspring) %>
      <%= link_to hotspring_like_path(@hotspring), method: :delete do %>
        <i class="fas fa-heart"></i><%= @hotspring.likes.count %>
      <% end %>
    <% else %>
      <%= link_to hotspring_likes_path(@hotspring), method: :post do %>
        <i class="far fa-heart"></i><%= @hotspring.likes.count %>
      <% end %>
    <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= @hotspring.likes.count %>
  <% end %>
  <%= link_to "編集する", edit_hotspring_path(@hotspring.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @hotspring.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>
  <div class="image-top">
  <%= image_tag @hotspring.resize_image_top if @hotspring.image_top.attached? %>
</div>

  <% if user_signed_in? %>
    <%= form_with(model: [@hotspring, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<%= link_to "温泉一覧に戻る", hotsprings_path %>
<%= link_to "編集する", edit_hotspring_path(@hotspring.id) %>

app/views/hotsprings/top.html.erb
<div id="top">
    <div class="background">
    </div>
    <div class="image">
        <div class="image_wrap">
            <ul class="image_list image_list--left">
                <li class="image_item"><%= image_tag '0003629534_kusatsu_couple_MV.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag 'J19986.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag 'onsen0037797.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag 'o4001277001-1-1.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag '20181203ta02.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag 'af3ad990-089a-4b41-a529-a6e8c8d0c63a_l.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
            </ul>
            <ul class="image_list image_list--left">
                <li class="image_item"><%= image_tag '0003629534_kusatsu_couple_MV.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag 'J19986.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag 'onsen0037797.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag 'o4001277001-1-1.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag '20181203ta02.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
                <li class="image_item"><%= image_tag 'af3ad990-089a-4b41-a529-a6e8c8d0c63a_l.jpg', :class=>"cat-icon", :alt => 'mentor' %></li>
            </ul>
        </div>
    </div>
    <div class="background2">
        <div class="setumei">
            温泉選びに悩んだ経験はありませんか？
            <br><br><br>
            日本では温泉施設の数が非常に多く、20,000件を超えます。
            <br><br><br>
            またこの数字は日本の47都道府県すべてに、<br><br>
            温泉地や温泉の宿泊施設があるということにもなります。
            <br><br><br>
            そこで「温泉日記」を使って条件に合う新たな温泉と出会い、<br><br>
            行った記録を残しませんか♨
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/~~~~~~"  crossorigin="anonymous"></script> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <h1><%= link_to "温泉日記", hotsprings_top_path %></h1>
      <div class="header-list">
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to "温泉一覧", hotsprings_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "一覧", hotsprings_path %></li>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </header>
    <main>
      <div class="background">
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>